# Generated by Django 3.2.8 on 2021-12-02 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cd_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Prüfungstermin')),
                ('start_time', models.TimeField(null=True, verbose_name='Prüfungsbeginn')),
                ('end_time', models.TimeField(null=True, verbose_name='Prüfungsende')),
                ('type', models.CharField(choices=[('K', 'Klausur'), ('C', 'Computerklausur'), ('P', 'Präsentation'), ('SE', 'Hausarbeit'), ('PR', 'Projektarbeit'), ('M', 'Mündliche Prüfung'), ('BT', 'Bachelor Thesis')], max_length=2, verbose_name='Prüfungsart')),
                ('enrollmentDeadline', models.DateTimeField(null=True, verbose_name='Anmeldeschluss')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Kommentar')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cd_core.module', verbose_name='Modul')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cd_core.room', verbose_name='Raum')),
                ('seminargroup', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cd_core.seminargroup', verbose_name='Seminargruppe')),
            ],
            options={
                'verbose_name': 'Prüfung',
                'verbose_name_plural': 'Prüfungen',
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluationCompletion', models.DateTimeField(null=True, verbose_name='Beurteilung vom')),
                ('results', models.TextField(help_text='Bitte geben Sie die Ergebnisse in folgender Form ein:</br>\n            <b>Matrikelnummer, Note ohne Komma,</b></br> \n            Beispiel: 5001001, 27,</br>\n            (Noten: 1,0 = 10; 1,3 = 13; 2,7 = 27; etc.)</br>\n            (Zeilenumbrüche sind gestattet)', verbose_name='Ergebnisse')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Veröffentlicht am')),
                ('lastEdited', models.DateTimeField(auto_now=True, null=True, verbose_name='Zuletzt geändert am')),
                ('examination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cd_examination.examination', verbose_name='Prüfung')),
            ],
            options={
                'verbose_name': 'Prüfungsergebnis',
                'verbose_name_plural': 'Prüfungsergebnisse',
            },
        ),
        migrations.CreateModel(
            name='ExamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.PositiveSmallIntegerField(editable=False, null=True, verbose_name='Versuch')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Angemeldet am')),
                ('result', models.DecimalField(decimal_places=1, editable=False, max_digits=3, null=True, verbose_name='Ergebnis')),
                ('evaluationCompletion', models.DateTimeField(editable=False, null=True, verbose_name='Beurteilung vom')),
                ('resultPublication', models.DateTimeField(editable=False, null=True, verbose_name='Veröffentlicht am')),
                ('examination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cd_examination.examination', verbose_name='Prüfung')),
                ('participant', models.ForeignKey(limit_choices_to={'role': 'Stu'}, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Teilnehmer')),
            ],
            options={
                'verbose_name': 'Prüfungsanmeldung',
                'verbose_name_plural': 'Prüfungsanmeldungen',
                'unique_together': {('examination', 'participant', 'evaluationCompletion')},
            },
        ),
    ]
