# Generated by Django 3.2.8 on 2021-12-06 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cd_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cd_examination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='Ergebnis')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cd_core.module', verbose_name='Modul')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'Stu'}, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Prüfungsanerkennung',
                'verbose_name_plural': 'Prüfungsanerkennungen',
                'unique_together': {('user', 'module')},
            },
        ),
    ]
