# Generated by Django 3.2.8 on 2021-12-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cd_examination', '0002_examrecognition'),
    ]

    operations = [
        migrations.AddField(
            model_name='examrecognition',
            name='createdAt',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Anerkannt am'),
        ),
        migrations.AddField(
            model_name='examrecognition',
            name='lastEditedAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='zuletzt editiert am'),
        ),
    ]
